---
- hosts: all
  become: yes
  name: "NTP configuration"

  tasks:
    - name: "Ensure NTP is installed"
      apt:
        name:
          - ntp
        state: present

    - name: "Ensure NTP is started now and at boot"
      service:
        name: ntp
        state: started
        enabled: yes
